-- Current 300-ward structure (GHMC/CMC/MMC combined), effective from the
-- delimitation gazette notification: Telangana Gazette Extraordinary No. 773,
-- 25 Dec 2025 ("Delimitation of wards in Greater Hyderabad Municipal
-- Corporation" -- https://www.ghmc.gov.in/quicklinks/Notification%20on%20delimitation%20300%20wards%20in%20GHMC.pdf).
--
-- Ward numbers, names, zone and circle assignment transcribed from Wikipedia's
-- "Administrative divisions of Hyderabad" (List of wards in CURE zone table),
-- which cites the same gazette. NOT taken on trust: cross-checked 9 wards
-- (95-98, 171-175) directly against the gazette's own extractable text pages
-- (most of the 161-page PDF is scanned/non-extractable, these were the pages
-- that had a real text layer). Found and fixed ONE transposition error --
-- wards 95/96 were swapped in the Wikipedia table (gazette page 50: 95 =
-- Azampura, 96 = Kala Dera). Everything else in the sample matched exactly
-- (two harmless spelling variants: Pathargatti/Pathergatti,
-- Sitaphalmandi/Seethaphalmandi -- same place, transliteration only).
--
-- Zone-to-corporation split (GHMC 150 / CMC 76 / MMC 74 = 300) is the
-- Wikipedia "GHMC split (2026-present)" table, itself citing separate news
-- sources for the 11 Feb 2026 trifurcation -- this is what determines each
-- ward's civic_body_id below (via its zone, already seeded in V2).
--
-- What this migration does NOT claim: reservation_category (ST/SC/BC/GEN/
-- GEN_WOMEN -- notified Jan 2026 but only as zone-level counts, not a
-- per-ward mapping we have access to), population_est, or geometry. Left
-- NULL rather than fabricated, per the schema's own honesty-by-default rule.
--
-- valid_from is the gazette date (2025-12-25), not the later 11 Feb 2026
-- trifurcation date -- that's when THIS ward version (number/name/boundary)
-- came into force. The trifurcation didn't change ward boundaries, only
-- which civic_body administers each one.

INSERT INTO circle (zone_id, name, code)
SELECT z.id, c.circle_name, c.circle_code
FROM (VALUES
    ('Malkajgiri', 'Keesara', '1'),
    ('Malkajgiri', 'Alwal', '2'),
    ('Malkajgiri', 'Bowenpally', '3'),
    ('Malkajgiri', 'Moula Ali', '4'),
    ('Malkajgiri', 'Malkajgiri', '5'),
    ('Uppal', 'Ghatkesar', '6'),
    ('Uppal', 'Kapra', '7'),
    ('Uppal', 'Nacharam', '8'),
    ('Uppal', 'Uppal', '9'),
    ('Uppal', 'Boduppal', '10'),
    ('LB Nagar', 'Nagole', '11'),
    ('LB Nagar', 'Saroornagar', '12'),
    ('LB Nagar', 'L. B. Nagar', '13'),
    ('LB Nagar', 'Hayathnagar', '14'),
    ('Shamshabad', 'Adibatla', '15'),
    ('Shamshabad', 'Badangpet', '16'),
    ('Shamshabad', 'Jalpally', '17'),
    ('Shamshabad', 'Shamshabad', '18'),
    ('Rajendranagar', 'Rajendranagar', '19'),
    ('Rajendranagar', 'Attapur', '20'),
    ('Rajendranagar', 'Bahadurpura', '21'),
    ('Rajendranagar', 'Falaknuma', '22'),
    ('Rajendranagar', 'Chandrayan Gutta', '23'),
    ('Rajendranagar', 'Jangammet', '24'),
    ('Charminar', 'Santoshnagar', '25'),
    ('Charminar', 'Yakutpura', '26'),
    ('Charminar', 'Malakpet', '27'),
    ('Charminar', 'Charminar', '28'),
    ('Charminar', 'Moosarambagh', '29'),
    ('Golconda', 'Goshamahal', '30'),
    ('Golconda', 'Karwan', '31'),
    ('Golconda', 'Golconda', '32'),
    ('Golconda', 'Mehdipatnam', '33'),
    ('Golconda', 'Masab Tank', '34'),
    ('Khairtabad', 'Khairatabad', '35'),
    ('Khairtabad', 'Jubilee Hills', '36'),
    ('Khairtabad', 'Borabanda', '37'),
    ('Khairtabad', 'Yousufguda', '38'),
    ('Khairtabad', 'Ameerpet', '39'),
    ('Secunderabad', 'Kavadiguda', '40'),
    ('Secunderabad', 'Musheerabad', '41'),
    ('Secunderabad', 'Amberpet', '42'),
    ('Secunderabad', 'Tarnaka', '43'),
    ('Secunderabad', 'Mettuguda', '44'),
    ('Serilingampally', 'Narsingi', '45'),
    ('Serilingampally', 'Patancheruvu', '46'),
    ('Serilingampally', 'Ameenpur', '47'),
    ('Serilingampally', 'Miyapur', '48'),
    ('Serilingampally', 'Serilingampally', '49'),
    ('Kukatpally', 'Madhapur', '50'),
    ('Kukatpally', 'Allwyn Colony', '51'),
    ('Kukatpally', 'Kukatpally', '52'),
    ('Kukatpally', 'Moosapet', '53'),
    ('Qutbullapur', 'Chintal', '54'),
    ('Qutbullapur', 'Jeedimetla', '55'),
    ('Qutbullapur', 'Kompally', '56'),
    ('Qutbullapur', 'Gajularamaram', '57'),
    ('Qutbullapur', 'Nizampet', '58'),
    ('Qutbullapur', 'Dundigal', '59'),
    ('Qutbullapur', 'Medchal', '60')
) AS c(zone_name, circle_name, circle_code)
JOIN zone z ON z.name = c.zone_name;

INSERT INTO ward (ward_number, name, circle_id, civic_body_id, valid_from)
SELECT w.ward_number, w.ward_name, ci.id, z.civic_body_id, DATE '2025-12-25'
FROM (VALUES
    (1, 'Keesara', 'Malkajgiri', '1'),
    (2, 'Chandrapuri Colony', 'Malkajgiri', '1'),
    (3, 'Jawaharnagar', 'Malkajgiri', '1'),
    (4, 'Dammaiguda', 'Malkajgiri', '1'),
    (5, 'Nagaram', 'Uppal', '6'),
    (6, 'Ghatkesar', 'Uppal', '6'),
    (7, 'Edulabad', 'Uppal', '6'),
    (8, 'Pocharam', 'Uppal', '6'),
    (9, 'Medipally', 'Uppal', '10'),
    (10, 'Peerzadiguda', 'Uppal', '10'),
    (11, 'Boduppal', 'Uppal', '10'),
    (12, 'Chengicherla', 'Uppal', '10'),
    (13, 'Vampuguda', 'Uppal', '7'),
    (14, 'Kapra', 'Uppal', '7'),
    (15, 'A. S. Rao Nagar', 'Uppal', '7'),
    (16, 'Kushaiguda', 'Uppal', '7'),
    (17, 'Cherlapally', 'Uppal', '7'),
    (18, 'Shakthi Sai Nagar', 'Uppal', '8'),
    (19, 'H. B. Colony', 'Uppal', '8'),
    (20, 'Mallapur', 'Uppal', '8'),
    (21, 'Nacharam', 'Uppal', '8'),
    (22, 'HMT Nagar', 'Uppal', '8'),
    (23, 'Chilkanagar', 'Uppal', '9'),
    (24, 'Beerappagadda', 'Uppal', '9'),
    (25, 'Habsiguda', 'Uppal', '9'),
    (26, 'Ramanthapur', 'Uppal', '9'),
    (27, 'Venkat Reddy Nagar', 'Uppal', '9'),
    (28, 'Uppal', 'Uppal', '9'),
    (29, 'Nagole', 'LB Nagar', '11'),
    (30, 'Kothapet', 'LB Nagar', '12'),
    (31, 'Chaitanyapuri', 'LB Nagar', '12'),
    (32, 'Gaddiannaram', 'LB Nagar', '12'),
    (33, 'Saroornagar', 'LB Nagar', '12'),
    (34, 'Doctors Colony', 'LB Nagar', '12'),
    (35, 'Rama Krishna Puram', 'LB Nagar', '12'),
    (36, 'NTR Nagar', 'LB Nagar', '12'),
    (37, 'Lingojiguda', 'LB Nagar', '13'),
    (38, 'Champapet', 'LB Nagar', '13'),
    (39, 'Karmanghat', 'LB Nagar', '13'),
    (40, 'Bairamalguda', 'LB Nagar', '13'),
    (41, 'Hastinapuram', 'LB Nagar', '13'),
    (42, 'BN Reddy Nagar', 'LB Nagar', '14'),
    (43, 'Vanasthalipuram', 'LB Nagar', '14'),
    (44, 'Chintalakunta', 'LB Nagar', '14'),
    (45, 'Mansoorabad', 'LB Nagar', '11'),
    (46, 'Geological Survey of India', 'LB Nagar', '11'),
    (47, 'Lecturers Colony', 'LB Nagar', '11'),
    (48, 'High Court Colony', 'LB Nagar', '14'),
    (49, 'Sahebnagar', 'LB Nagar', '14'),
    (50, 'Hayathnagar', 'LB Nagar', '14'),
    (51, 'Kuntloor', 'LB Nagar', '11'),
    (52, 'Pedda Amberpet', 'LB Nagar', '11'),
    (53, 'Thorrur', 'Shamshabad', '15'),
    (54, 'Kongara Kalan', 'Shamshabad', '15'),
    (55, 'Adibatla', 'Shamshabad', '15'),
    (56, 'Turkayamjal', 'Shamshabad', '15'),
    (57, 'Nadergul', 'Shamshabad', '16'),
    (58, 'Prasanthi Hills', 'Shamshabad', '16'),
    (59, 'Jillelguda', 'Shamshabad', '16'),
    (60, 'Meerpet', 'Shamshabad', '16'),
    (61, 'Badangpet', 'Shamshabad', '16'),
    (62, 'Balapur', 'Shamshabad', '16'),
    (63, 'Shaheen Nagar', 'Shamshabad', '17'),
    (64, 'Pahari Sharif', 'Shamshabad', '17'),
    (65, 'Jalpally', 'Shamshabad', '17'),
    (66, 'Tukkuguda', 'Shamshabad', '18'),
    (67, 'Mankhal', 'Shamshabad', '18'),
    (68, 'Bandlaguda', 'Rajendranagar', '23'),
    (69, 'Noori Nagar', 'Rajendranagar', '23'),
    (70, 'Barkas', 'Rajendranagar', '23'),
    (71, 'Kanchanbagh', 'Rajendranagar', '23'),
    (72, 'Chandrayan Gutta', 'Rajendranagar', '23'),
    (73, 'Riyasat Nagar', 'Rajendranagar', '24'),
    (74, 'Lalitha Bagh', 'Rajendranagar', '24'),
    (75, 'Jangammet', 'Rajendranagar', '24'),
    (76, 'Phool Bagh', 'Rajendranagar', '24'),
    (77, 'Quadri Chaman', 'Rajendranagar', '24'),
    (78, 'Gowlipura', 'Charminar', '26'),
    (79, 'Talab Chanchalam', 'Charminar', '26'),
    (80, 'Yakutpura', 'Charminar', '26'),
    (81, 'Dabirpura', 'Charminar', '26'),
    (82, 'Rein Bazar', 'Charminar', '26'),
    (83, 'Madannapet', 'Charminar', '26'),
    (84, 'Bhanu Nagar', 'Charminar', '25'),
    (85, 'Santoshnagar', 'Charminar', '25'),
    (86, 'IS SADAN', 'Charminar', '25'),
    (87, 'Saraswathi Nagar', 'Charminar', '25'),
    (88, 'Saidabad', 'Charminar', '27'),
    (89, 'Asmangadh', 'Charminar', '27'),
    (90, 'Moosarambagh', 'Charminar', '29'),
    (91, 'Old Malakpet', 'Charminar', '29'),
    (92, 'MCH Colony', 'Charminar', '29'),
    (93, 'Akberbagh', 'Charminar', '27'),
    (94, 'Chawani', 'Charminar', '27'),
    (95, 'Azampura', 'Charminar', '29'),
    (96, 'Kala Dera', 'Charminar', '29'),
    (97, 'Purani Haveli', 'Charminar', '28'),
    (98, 'Pathargatti', 'Charminar', '28'),
    (99, 'Hari Bowli', 'Charminar', '28'),
    (100, 'Qazipura', 'Charminar', '28'),
    (101, 'Ghansi Bazar', 'Charminar', '28'),
    (102, 'Purana Pul', 'Charminar', '28'),
    (103, 'Doodh Bowli', 'Rajendranagar', '21'),
    (104, 'Shah-Ali-Banda', 'Rajendranagar', '22'),
    (105, 'Falaknuma', 'Rajendranagar', '22'),
    (106, 'Jahanuma', 'Rajendranagar', '22'),
    (107, 'Nawab Saheb Kunta', 'Rajendranagar', '22'),
    (108, 'Teegal Kunta', 'Rajendranagar', '21'),
    (109, 'Chandu Lal Baradari', 'Rajendranagar', '21'),
    (110, 'Ramnasthpura', 'Rajendranagar', '21'),
    (111, 'Kishanbagh', 'Rajendranagar', '21'),
    (112, 'Attapur', 'Rajendranagar', '20'),
    (113, 'Hyderguda', 'Rajendranagar', '20'),
    (114, 'Suleman Nagar', 'Rajendranagar', '20'),
    (115, 'Shastripuram', 'Rajendranagar', '20'),
    (116, 'Katedan', 'Rajendranagar', '20'),
    (117, 'Mailardevpally', 'Rajendranagar', '20'),
    (118, 'Shamshabad', 'Shamshabad', '18'),
    (119, 'Kothwalguda', 'Shamshabad', '18'),
    (120, 'Rajendranagar', 'Rajendranagar', '19'),
    (121, 'Bandlaguda Jagir', 'Rajendranagar', '19'),
    (122, 'Kismatpur', 'Rajendranagar', '19'),
    (123, 'Hydershahkote', 'Rajendranagar', '19'),
    (124, 'Narsingi', 'Serilingampally', '45'),
    (125, 'Kokapet', 'Serilingampally', '45'),
    (126, 'Gandipet', 'Serilingampally', '45'),
    (127, 'Manikonda', 'Serilingampally', '45'),
    (128, 'Neknampur', 'Serilingampally', '45'),
    (129, 'Nizam Colony', 'Golconda', '32'),
    (130, 'Nanalnagar', 'Golconda', '32'),
    (131, 'Tolichowki', 'Golconda', '32'),
    (132, 'Golconda', 'Golconda', '32'),
    (133, 'Ibrahimbagh', 'Golconda', '32'),
    (134, 'Langar Houz', 'Golconda', '31'),
    (135, 'Gudimalkapur', 'Golconda', '31'),
    (136, 'Karwan', 'Golconda', '31'),
    (137, 'Tappachabutra', 'Golconda', '31'),
    (138, 'Jiyaguda', 'Golconda', '31'),
    (139, 'Asif Nagar', 'Golconda', '33'),
    (140, 'Padmanabha Nagar', 'Golconda', '33'),
    (141, 'Mehdipatnam', 'Golconda', '33'),
    (142, 'Syed Nagar', 'Golconda', '33'),
    (143, 'Vijayanagar Colony', 'Golconda', '34'),
    (144, 'Ahmed Nagar', 'Golconda', '34'),
    (145, 'Shanthi Nagar', 'Golconda', '34'),
    (146, 'Red Hills', 'Khairtabad', '35'),
    (147, 'Mallepally', 'Golconda', '34'),
    (148, 'Dattatreya Nagar', 'Golconda', '30'),
    (149, 'Manghalhat', 'Golconda', '30'),
    (150, 'Goshamahal', 'Golconda', '30'),
    (151, 'Begum Bazaar', 'Golconda', '30'),
    (152, 'Jambagh', 'Golconda', '30'),
    (153, 'Exhibition Grounds', 'Golconda', '30'),
    (154, 'Gunfoundry', 'Khairtabad', '35'),
    (155, 'Barkatpura', 'Secunderabad', '42'),
    (156, 'Kachiguda', 'Secunderabad', '42'),
    (157, 'Golnaka', 'Secunderabad', '42'),
    (158, 'Patel Nagar', 'Secunderabad', '42'),
    (159, 'Amberpet', 'Secunderabad', '42'),
    (160, 'Bagh Amberpet', 'Secunderabad', '42'),
    (161, 'Tilak Nagar', 'Secunderabad', '42'),
    (162, 'Nallakunta', 'Secunderabad', '42'),
    (163, 'Adikmet', 'Secunderabad', '41'),
    (164, 'Bagh Lingampally', 'Secunderabad', '41'),
    (165, 'Gandhi Nagar', 'Secunderabad', '40'),
    (166, 'Kavadiguda', 'Secunderabad', '40'),
    (167, 'Bakaram', 'Secunderabad', '40'),
    (168, 'Bholakpur', 'Secunderabad', '40'),
    (169, 'Musheerabad', 'Secunderabad', '41'),
    (170, 'Ramnagar', 'Secunderabad', '41'),
    (171, 'Bapuji Nagar', 'Secunderabad', '41'),
    (172, 'Boudha Nagar', 'Secunderabad', '43'),
    (173, 'Tarnaka', 'Secunderabad', '43'),
    (174, 'Sitaphalmandi', 'Secunderabad', '43'),
    (175, 'Chilkalguda', 'Secunderabad', '43'),
    (176, 'Mettuguda', 'Secunderabad', '44'),
    (177, 'Lalapet', 'Secunderabad', '44'),
    (178, 'North Lallaguda', 'Secunderabad', '44'),
    (179, 'Addagutta', 'Secunderabad', '44'),
    (180, 'East Anandbagh', 'Malkajgiri', '5'),
    (181, 'Mirjalguda', 'Malkajgiri', '5'),
    (182, 'Gautham Nagar', 'Malkajgiri', '5'),
    (183, 'Malkajgiri', 'Malkajgiri', '5'),
    (184, 'Balram Nagar', 'Malkajgiri', '4'),
    (185, 'Vinayak Nagar', 'Malkajgiri', '4'),
    (186, 'Moula Ali', 'Malkajgiri', '4'),
    (187, 'Kakatiya Nagar', 'Malkajgiri', '4'),
    (188, 'Neredmet', 'Malkajgiri', '4'),
    (189, 'Yapral', 'Malkajgiri', '1'),
    (190, 'Turakapally', 'Malkajgiri', '2'),
    (191, 'Macha Bollaram', 'Malkajgiri', '2'),
    (192, 'Alwal', 'Malkajgiri', '2'),
    (193, 'Venkatapuram', 'Malkajgiri', '2'),
    (194, 'Bhudevi Nagar', 'Malkajgiri', '2'),
    (195, 'Kanajiguda', 'Malkajgiri', '2'),
    (196, 'Monda Market', 'Malkajgiri', '3'),
    (197, 'Padmarao Nagar', 'Secunderabad', '40'),
    (198, 'Bansilalpet', 'Secunderabad', '40'),
    (199, 'Ramgopalpet', 'Secunderabad', '40'),
    (200, 'Begumpet', 'Khairtabad', '39'),
    (201, 'Ameerpet', 'Khairtabad', '39'),
    (202, 'S. R. Nagar', 'Khairtabad', '39'),
    (203, 'BK Guda', 'Khairtabad', '39'),
    (204, 'Sanathnagar', 'Khairtabad', '39'),
    (205, 'Erragadda', 'Khairtabad', '38'),
    (206, 'Vengal Rao Nagar', 'Khairtabad', '38'),
    (207, 'Srinagar Colony', 'Khairtabad', '38'),
    (208, 'Yousufguda', 'Khairtabad', '38'),
    (209, 'AG Colony', 'Khairtabad', '38'),
    (210, 'Krishna Nagar', 'Khairtabad', '37'),
    (211, 'Rahmath Nagar', 'Khairtabad', '37'),
    (212, 'Karmika Nagar', 'Khairtabad', '37'),
    (213, 'Rajeev Nagar', 'Khairtabad', '37'),
    (214, 'Borabanda', 'Khairtabad', '37'),
    (215, 'Jubilee Hills', 'Khairtabad', '36'),
    (216, 'Venkateswara Colony', 'Khairtabad', '36'),
    (217, 'Irrum Manzil', 'Khairtabad', '35'),
    (218, 'Somajiguda', 'Khairtabad', '35'),
    (219, 'Khairatabad', 'Khairtabad', '35'),
    (220, 'Himayatnagar', 'Khairtabad', '35'),
    (221, 'Banjara Hills', 'Khairtabad', '36'),
    (222, 'Film Nagar', 'Khairtabad', '36'),
    (223, 'Shaikpet', 'Golconda', '32'),
    (224, 'OU Colony', 'Golconda', '32'),
    (225, 'Gachibowli', 'Serilingampally', '49'),
    (226, 'Nallagandla', 'Serilingampally', '49'),
    (227, 'Serilingampally', 'Serilingampally', '49'),
    (228, 'Masjid Banda', 'Serilingampally', '49'),
    (229, 'Sri Ram Nagar', 'Serilingampally', '49'),
    (230, 'Anjaiah Nagar', 'Kukatpally', '50'),
    (231, 'HITEC City', 'Kukatpally', '50'),
    (232, 'Madhapur', 'Kukatpally', '50'),
    (233, 'Izzat Nagar', 'Kukatpally', '50'),
    (234, 'Kondapur', 'Serilingampally', '49'),
    (235, 'Matrusri Nagar', 'Kukatpally', '50'),
    (236, 'Hafeezpet', 'Serilingampally', '48'),
    (237, 'Madeenaguda', 'Serilingampally', '48'),
    (238, 'Chanda Nagar', 'Serilingampally', '48'),
    (239, 'Deepthisri Nagar', 'Serilingampally', '48'),
    (240, 'Miyapur', 'Serilingampally', '48'),
    (241, 'Maktha Mahabubpet', 'Serilingampally', '48'),
    (242, 'Mayuri Nagar', 'Kukatpally', '50'),
    (243, 'Hyder Nagar', 'Kukatpally', '51'),
    (244, 'Bhagya Nagar Colony', 'Kukatpally', '51'),
    (245, 'Shamshiguda', 'Kukatpally', '51'),
    (246, 'Allwyn Colony', 'Kukatpally', '51'),
    (247, 'Vivekananda Nagar Colony', 'Kukatpally', '51'),
    (248, 'Venkateswara Nagar', 'Kukatpally', '51'),
    (249, 'Kukatpally', 'Kukatpally', '52'),
    (250, 'Balaji Nagar', 'Kukatpally', '52'),
    (251, 'Vasanth Nagar', 'Kukatpally', '52'),
    (252, 'KPHB Colony', 'Kukatpally', '52'),
    (253, 'Kaithalapur', 'Kukatpally', '52'),
    (254, 'Gayatri Nagar', 'Kukatpally', '52'),
    (255, 'Allapur', 'Kukatpally', '53'),
    (256, 'Moti Nagar', 'Kukatpally', '53'),
    (257, 'Moosapet', 'Kukatpally', '53'),
    (258, 'Prashanth Nagar', 'Kukatpally', '53'),
    (259, 'Balanagar', 'Kukatpally', '53'),
    (260, 'Fateh Nagar', 'Malkajgiri', '3'),
    (261, 'Prakash Nagar', 'Malkajgiri', '3'),
    (262, 'Old Bowenpally', 'Malkajgiri', '3'),
    (263, 'Tellapur', 'Serilingampally', '46'),
    (264, 'Hasmathpet', 'Malkajgiri', '3'),
    (265, 'Muthangi', 'Serilingampally', '46'),
    (266, 'Patancheruvu', 'Serilingampally', '46'),
    (267, 'JP Colony', 'Serilingampally', '46'),
    (268, 'Ramachandrapuram', 'Serilingampally', '47'),
    (269, 'Bharathi Nagar', 'Serilingampally', '47'),
    (270, 'Beeramguda', 'Serilingampally', '47'),
    (271, 'Ameenpur', 'Serilingampally', '47'),
    (272, 'IDA Bollaram', 'Serilingampally', '47'),
    (273, 'Nizampet', 'Qutbullapur', '58'),
    (274, 'Bachupally', 'Qutbullapur', '58'),
    (275, 'Bandari Layout', 'Qutbullapur', '58'),
    (276, 'Pragathi Nagar', 'Qutbullapur', '58'),
    (277, 'Mahadevpuram', 'Qutbullapur', '57'),
    (278, 'Gajularamaram', 'Qutbullapur', '57'),
    (279, 'Rodamestri Nagar', 'Qutbullapur', '54'),
    (280, 'Jagathgiri Gutta', 'Qutbullapur', '54'),
    (281, 'Ranga Reddy Nagar', 'Qutbullapur', '54'),
    (282, 'Chintal', 'Qutbullapur', '54'),
    (283, 'Giri Nagar', 'Qutbullapur', '54'),
    (284, 'Ganesh Nagar', 'Qutbullapur', '55'),
    (285, 'Padma Nagar', 'Qutbullapur', '55'),
    (286, 'Quthbullapur', 'Qutbullapur', '55'),
    (287, 'Pet Basheerabad', 'Qutbullapur', '55'),
    (288, 'Kompally', 'Qutbullapur', '56'),
    (289, 'Dulapally', 'Qutbullapur', '56'),
    (290, 'Subhash Nagar', 'Qutbullapur', '56'),
    (291, 'Shapur Nagar', 'Qutbullapur', '57'),
    (292, 'Saibaba Nagar', 'Qutbullapur', '56'),
    (293, 'Suraram', 'Qutbullapur', '57'),
    (294, 'Bahadurpally', 'Qutbullapur', '59'),
    (295, 'Bowrampet', 'Qutbullapur', '59'),
    (296, 'Dundigal', 'Qutbullapur', '59'),
    (297, 'Medchal', 'Qutbullapur', '60'),
    (298, 'Pudur-Kistapur', 'Qutbullapur', '60'),
    (299, 'Gundlapochampally', 'Qutbullapur', '60'),
    (300, 'Shamirpet', 'Malkajgiri', '1')
) AS w(ward_number, ward_name, zone_name, circle_code)
JOIN zone z ON z.name = w.zone_name
JOIN circle ci ON ci.zone_id = z.id AND ci.code = w.circle_code;
